version: '3'

services:
    # Create a service called web
    web:
      # Build an image from the files in the project root directory (Dockerfile)
      build: .
      # Assign a name for the container. 
      container_name: vipertasks
      ports:
        - "8000:80"
      command: >
        sh -c "python vipertasks/manage.py migrate && python vipertasks/manage.py runserver 0.0.0.0:8000 --noreload --nothreading"